services:
  backend:
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - '8080:8080'
    networks:
      - app-networks

  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - '5173:80'
    networks:
      - app-networks

networks:
  app-networks:
    driver: bridge
